//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub mod prelude;

pub mod bancho_client_hardware_records;
pub mod beatmap_ratings;
pub mod beatmaps;
pub mod channel_privileges;
pub mod channel_users;
pub mod channels;
pub mod chat_messages;
pub mod favourite_beatmaps;
pub mod followers;
pub mod leaderboard;
pub mod privileges;
pub mod score_pp;
pub mod scores;
pub mod scores_classic;
pub mod scores_generic;
pub mod sea_orm_active_enums;
pub mod user_pp;
pub mod user_privileges;
pub mod user_settings;
pub mod user_stats;
pub mod users;
