//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::bancho_client_hardware_records::Entity as BanchoClientHardwareRecords;
pub use super::beatmap_ratings::Entity as BeatmapRatings;
pub use super::beatmaps::Entity as Beatmaps;
pub use super::channel_privileges::Entity as ChannelPrivileges;
pub use super::channel_users::Entity as ChannelUsers;
pub use super::channels::Entity as Channels;
pub use super::chat_messages::Entity as ChatMessages;
pub use super::favourite_beatmaps::Entity as FavouriteBeatmaps;
pub use super::followers::Entity as Followers;
pub use super::leaderboard::Entity as Leaderboard;
pub use super::privileges::Entity as Privileges;
pub use super::score_pp::Entity as ScorePp;
pub use super::scores::Entity as Scores;
pub use super::scores_classic::Entity as ScoresClassic;
pub use super::scores_generic::Entity as ScoresGeneric;
pub use super::user_pp::Entity as UserPp;
pub use super::user_privileges::Entity as UserPrivileges;
pub use super::user_settings::Entity as UserSettings;
pub use super::user_stats::Entity as UserStats;
pub use super::users::Entity as Users;
